apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kappnav.app.auto-create.name: auto1-app
  name: auto1
  labels:
    app: auto1-app
    kappnav.app.auto-create: "true"
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auto1-app
  template:
    metadata:
      labels:
        app: auto1-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
