apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto0
  labels:
    app: auto0
    kappnav.app.auto-create: "true"
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auto0
  template:
    metadata:
      labels:
        app: auto0
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
